services:
  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql
      args:
        PG_VERSION: ${POSTGRESQL_VERSION}
    restart: always
    ports:
      - ${POSTGRESQL_HOST}:${POSTGRESQL_PORT}:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/${POSTGRESQL_VERSION}/docker
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}

  redis:
    container_name: redis
    image: bitnami/redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  minio:
    container_name: minio
    image: minio/minio:${MINIO_VERSION}
    restart: always
    ports:
      - ${MINIO_HOST}:${MINIO_API_PORT}:9000
      - ${MINIO_HOST}:${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
